.travis.yml

Add mongodb to Travis to fix the build and bump the scala version

Add mongodb to Travis

---

.travis.yml

FSET-580 Run integration tests in Travis

---

app/connectors/AuthProviderClient.scala

Relies on internal PR - auth-provider/pull/43

Update clear database to take advantage of an updated auth provider endpoint

---

app/connectors/ExchangeObjects.scala
app/services/onlinetesting/OnlineTestService.scala
test/connectors/CubiksGatewayClientSpec.scala
test/services/onlinetesting/OnlineTestServiceSpec.scala

Changed fast track to work with the latest version of the Cubiks API for inviting applicants

FSET-1072 changes to work with latest Cubiks invite API

---

app/common/Constants.scala
app/model/ApplicationValidator.scala
app/repositories/application/GeneralApplicationRepository.scala
app/repositories/application/OnlineTestRepository.scala
app/repositories/application/TestDataRepository.scala
app/services/reporting/LocationProcessor.scala
app/services/reporting/SocioEconomicCalculator.scala
app/services/testdata/SubmittedStatusGenerator.scala
app/services/testdata/faker/DataFaker.scala
it/repositories/ApplicationRepositorySpec.scala
it/repositories/OnlineTestRepositorySpec.scala
it/repositories/application/GeneralApplicationMongoRepositorySpec.scala
it/services/OnlineTestRetrievePDFReportServiceIntegrationSpec.scala
it/services/OnlineTestServiceIntegrationSpec.scala
test/controllers/AssessmentScheduleControllerSpec.scala
test/controllers/AssistanceDetailsControllerSpec.scala
test/mocks/application/AssistanceDetailsInMemoryRepository.scala
test/mocks/application/DocumentRootInMemoryRepository.scala
test/services/ApplicationValidatorSpec.scala
test/services/reporting/SocioEconomicCalculatorSpec.scala

Some areas of code are using Yes/No and some are using yes/no.

Add constant values for Yes/No for use in json.

---

app/connectors/testdata/ExchangeObjects.scala
app/controllers/PersonalDetailsController.scala
app/model/ApplicationValidator.scala
app/model/PersistedObjects.scala
app/model/persisted/PersonalDetails.scala
app/repositories/FrameworkRepository.scala
app/repositories/application/PersonalDetailsRepository.scala
app/repositories/application/TestDataRepository.scala
app/repositories/package.scala
app/services/testdata/GeneratorConfig.scala
app/services/testdata/InProgressPersonalDetailsStatusGenerator.scala
app/services/testdata/SubmittedStatusGenerator.scala
it/repositories/application/PersonalDetailsMongoRepositorySpec.scala
test/controllers/AssessmentScheduleControllerSpec.scala
test/controllers/CandidateScoresControllerSpec.scala
test/controllers/PersonalDetailsControllerSpec.scala
test/mocks/application/PersonalDetailsInMemoryRepository.scala
test/services/ApplicationValidatorSpec.scala
test/services/locationschemes/LocationSchemeServiceSpec.scala

Manual BSON reader has been replaced by Macros.handler

Replace code to serialize/deserialize manually with Macros.handler

---

app/controllers/OnlineTestController.scala
project/build.properties
test/controllers/OnlineTestControllerSpec.scala

Return BadRequest if admin tried to reset an online test that is in an invalid application status.

FSET-1140 Reset Online Tests

---

app/connectors/testdata/ExchangeObjects.scala
app/services/testdata/AllocationStatusGenerator.scala
app/services/testdata/AssessmentResultNotifiedStatusGenerator.scala
app/services/testdata/AssessmentResultStatusGenerator.scala
app/services/testdata/AssessmentScoresAcceptedStatusGenerator.scala
app/services/testdata/AssessmentScoresEnteredStatusGenerator.scala
app/services/testdata/AwaitingAllocationNotifiedStatusGenerator.scala
app/services/testdata/AwaitingAllocationStatusGenerator.scala
app/services/testdata/AwaitingOnlineTestReevaluationStatusGenerator.scala
app/services/testdata/CreatedStatusGenerator.scala
app/services/testdata/FailedToAttendStatusGenerator.scala
app/services/testdata/InProgressAssistanceDetailsStatusGenerator.scala
app/services/testdata/InProgressPersonalDetailsStatusGenerator.scala
app/services/testdata/OnlineTestExpiredStatusGenerator.scala
app/services/testdata/OnlineTestFailedNotifiedStatusGenerator.scala
app/services/testdata/OnlineTestFailedStatusGenerator.scala
app/services/testdata/OnlineTestInvitedStatusGenerator.scala
app/services/testdata/OnlineTestStartedStatusGenerator.scala
app/services/testdata/RegisteredStatusGenerator.scala
app/services/testdata/StatusGeneratorFactory.scala
app/services/testdata/SubmittedStatusGenerator.scala
app/services/testdata/WithdrawnStatusGenerator.scala

AwaitingAllocationNotified generator.

Set the application status in the data generation response.

---

app/connectors/AuthProviderClient.scala
app/connectors/ExchangeObjects.scala
app/services/application/ApplicationService.scala
test/services/application/ApplicationServiceSpec.scala

This PR add the capability to update the candidate details via auth provider

Fix for buq reported in QA

---

project/plugins.sbt

Update play from version 2.5.8 to 2.5.12

---

app/repositories/application/GeneralApplicationRepository.scala

Fix indicator even when submitted applications don't have indicator doc

---

app/controllers/AssessmentCentreScoresController.scala
app/services/applicationassessment/AssessmentCentreScoresService.scala
test/services/applicationassessment/AssessmentCentreScoresServiceSpec.scala

reviewer scores already exist.

FSET-1426 Return a CONFLICT if an assessor tried to save or submit scores when

---

app/connectors/EmailClient.scala

FSET-1519 Update the email client to use the fsetfasttrack endpoint in the email

---

conf/assessment-centres.yaml
it/repositories/AssessmentCentreYamlRepositorySpec.scala

Acceptance tests were starting to fail because dates for this year had passed

Bump dev assessment centre dates by one year

---

app/services/testdata/AssessmentScoresStatusGenerator.scala
app/services/testdata/StatusGeneratorFactory.scala

It also includes changes in fasttrack-admin-frontend and fasttrack-admin-acceptance-tests

[Fset-1424] Link Assessment Centre scores and feedback from candidate info page

---

app/services/applicationassessment/AssessmentCentreScoresService.scala
test/services/applicationassessment/AssessmentCentreScoresServiceSpec.scala

so that we don't prevent the same assessor from updating the scores
they've already entered.

FSET-1523 Update the assessor scores check when saving to check the updatedBy ID

---

app/connectors/testdata/ExchangeObjects.scala
app/controllers/ReportingController.scala
app/model/ReportExchangeObjects.scala
app/repositories/application/ReportingRepoBSONReader.scala
app/repositories/application/ReportingRepository.scala
test/controllers/SubmitApplicationControllerSpec.scala
test/controllers/report/OnlineTestPassMarkModellingReportingControllerSpec.scala
test/controllers/report/SuccessfulCandidatesReportingControllerSpec.scala
test/model/exchange/ApplicationForCandidateProgressReportItemExamples.scala
test/model/exchange/CandidateProgressReportItemExamples.scala
test/model/exchange/LocationSchemesExamples.scala
test/services/ApplicationValidatorSpec.scala
test/services/locationschemes/LocationSchemeServiceSpec.scala

there is another PR in fasttrack-admin-frontend project

[Fset-1122] Successful candidate report

---

app/controllers/AssessmentCentreScoresController.scala
app/services/applicationassessment/AssessmentCentreScoresService.scala
conf/app.routes
test/controllers/AssessorScoresControllerSpec.scala
test/controllers/ReviewerScoresControllerSpec.scala

Added functionality to handle multiple reviewers simultaneously editing candidate scores and feedback

FSET-1537 Handle multiple reviewer updates

---

app/services/applicationassessment/AssessmentCentreScoresService.scala

Replace map with flatMap so the code that replaced the previous for comprehension is correct

FSET-1537 Replace map with flatMap

---

app/model/ReportExchangeObjects.scala
app/repositories/application/ReportingRepoBSONReader.scala
app/repositories/application/ReportingRepository.scala
test/controllers/report/SuccessfulCandidatesReportingControllerSpec.scala

2 PRs:
https://github.com/hmrc/fset-fasttrack/pull/171
csr-fasttrack-admin-frontend

[fset-1675] - Error in Fasttrack Successful candidates report

---

conf/locations-schemes.json

Added new policy scheme to locations-schemes.json so it is added everywhere the business scheme is

fset-1954 Added new policy scheme to locations-schemes.json

---

app/controllers/metrics/MetricsController.scala
app/repositories/application/GeneralApplicationRepository.scala

Implemented endpoint based on progress status time stamps (to work out the latest) as we did in fast stream

FSET-1964 implemented endpoint based on progress status time stamps

---

conf/locations-schemes.json

Add ProjectDelivery to Sheffield

---

conf/AssessmentCentreIndicatorLookup.csv
it/repositories/AssessmentCentreIndicatorCSVRepositorySpec.scala

Now sorted alphabetically, for your sanity

FSET-1953: Import faststream post code mapping

---

app/connectors/AuthProviderClient.scala
app/repositories/CollectionNames.scala

Aiming to merge and deploy on Thursday evening, not before

Update database names to 18 from 18test ahead of launch

---

conf/assessment-centres-prod.yaml

added 36 slots for am and pm for 23 and 24th May for London and Newcastle

FSET-2051 Updated the assessment centre prod yaml
